# Generated by Django 5.2.2 on 2025-07-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_certificate_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Контакты', max_length=200, verbose_name='Page Title')),
                ('subtitle', models.CharField(default='Свяжитесь с нами любым удобным способом', max_length=300, verbose_name='Page Subtitle')),
                ('phone', models.CharField(default='+7 (495) 025-25-01', max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(default='info@expoland.ru', max_length=254, verbose_name='Email Address')),
                ('address', models.CharField(default='Москва, улица Кульнева, 3с1', max_length=300, verbose_name='Office Address')),
                ('working_hours_weekdays', models.CharField(default='9:00 - 18:00', max_length=100, verbose_name='Working Hours (Mon-Fri)')),
                ('working_hours_saturday', models.CharField(default='10:00 - 16:00', max_length=100, verbose_name='Working Hours (Saturday)')),
                ('working_hours_sunday', models.CharField(default='Выходной', max_length=100, verbose_name='Working Hours (Sunday)')),
                ('map_latitude', models.DecimalField(decimal_places=6, default=55.742711, max_digits=10, verbose_name='Map Latitude')),
                ('map_longitude', models.DecimalField(decimal_places=6, default=37.523106, max_digits=10, verbose_name='Map Longitude')),
                ('map_zoom', models.IntegerField(default=15, verbose_name='Map Zoom Level')),
                ('description', models.TextField(blank=True, default='Мы всегда готовы ответить на ваши вопросы и помочь с выбором услуг. Звоните или пишите нам!', null=True, verbose_name='Additional Description')),
                ('whatsapp_link', models.URLField(blank=True, null=True, verbose_name='WhatsApp Link')),
                ('telegram_link', models.URLField(blank=True, null=True, verbose_name='Telegram Link')),
                ('vk_link', models.URLField(blank=True, null=True, verbose_name='VK Link')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Information',
                'verbose_name_plural': 'Contact Information',
                'ordering': ['-created_at'],
            },
        ),
    ]
