# Generated by Django 5.2.2 on 2025-07-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('company', models.CharField(blank=True, max_length=200, null=True, verbose_name='Компания')),
                ('service_type', models.CharField(choices=[('exhibition_stands', 'Выставочные стенды'), ('interior_design', 'Дизайн интерьера'), ('outdoor_advertising', 'Наружная реклама'), ('consultation', 'Консультация'), ('other', 'Другое')], default='consultation', max_length=50, verbose_name='Тип услуги')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема заявки')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('budget', models.CharField(blank=True, max_length=100, null=True, verbose_name='Бюджет')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Желаемый срок')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='new', max_length=20, verbose_name='Статус')),
                ('admin_notes', models.TextField(blank=True, null=True, verbose_name='Заметки администратора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
